import type {
  ArchitectingLineage,
  CompilerModule,
  FailureRecord,
  KnowledgeEntity,
  ProfileClaim,
  PromptRecord,
} from './types';

const promptEvidence = (id: string, label: string) => [
  {
    id: `EVIDENCE-${id}`,
    label,
    type: 'prompt' as const,
    locator: `fixture://${id}`,
    grade: 'SUPPORTED' as const,
  },
];

export const promptRecords: PromptRecord[] = [
  {
    libraryId: 'LTA-VISION-001',
    originalPromptId: 'P-CORE-001',
    title: 'What gets sold must determine delivery',
    project: 'QuietPilot',
    timestamp: '2026-04-23T23:39:33.688Z',
    family: 'visionary',
    form: 'reframe',
    originalText: 'QuietPilot is not a quoting tool or a CRM. What gets sold directly determines how work is delivered.',
    normalizedIntent: 'Define the product as one continuous commercial-to-operational system.',
    hiddenProblem: 'Disconnected sales and operations products lose the meaning of the accepted commitment.',
    principleIds: ['PRINCIPLE-ONE-AUTHORITY', 'PRINCIPLE-ACCEPTED-TRUTH'],
    patternIds: ['PATTERN-COMMERCIAL-SPINE'],
    lineageIds: ['LINEAGE-COMMERCIAL-SPINE'],
    impactScore: 99,
    reusabilityScore: 94,
    evidenceGrade: 'VERIFIED',
    tags: ['category-design', 'commercial-spine', 'operating-system'],
    evidence: promptEvidence('LTA-VISION-001', 'Product identity prompt'),
  },
  {
    libraryId: 'LTA-INQUISITOR-002',
    originalPromptId: 'P-AUDIT-002',
    title: 'Is the system lying about what it is?',
    project: 'QuietPilot',
    timestamp: '2026-04-23T23:40:00.000Z',
    family: 'inquisitor',
    form: 'challenge',
    originalText: 'Compare product intent, system enforcement, and runtime reality. Misalignment is system failure.',
    normalizedIntent: 'Audit claims against enforced code and runtime proof.',
    hiddenProblem: 'A convincing interface or document can overstate what the system actually guarantees.',
    principleIds: ['PRINCIPLE-EVIDENCE-BEFORE-CLAIMS'],
    patternIds: ['PATTERN-TRUTH-TRIANGULATION'],
    lineageIds: ['LINEAGE-TRUTH-HIERARCHY'],
    impactScore: 98,
    reusabilityScore: 99,
    evidenceGrade: 'VERIFIED',
    tags: ['adversarial-audit', 'truth', 'runtime'],
    evidence: promptEvidence('LTA-INQUISITOR-002', 'Intent/enforcement/runtime audit'),
  },
  {
    libraryId: 'LTA-ARCH-003',
    originalPromptId: 'P-ARCH-003',
    title: 'Find the authoritative root object',
    project: 'QuietPilot',
    timestamp: '2026-07-20T10:00:00.000Z',
    family: 'architecture',
    form: 'probe',
    originalText: 'Is Event truly the platform root, or is Engagement the neutral continuity object across verticals?',
    normalizedIntent: 'Select a domain root that preserves identity across vertical presentation packs.',
    hiddenProblem: 'A catering-specific aggregate name constrained a multi-vertical operating model.',
    principleIds: ['PRINCIPLE-ONE-AUTHORITY'],
    patternIds: ['PATTERN-ROOT-OBJECT-CUTOVER'],
    lineageIds: ['LINEAGE-ROOT-OBJECT'],
    impactScore: 96,
    reusabilityScore: 88,
    evidenceGrade: 'VERIFIED',
    tags: ['aggregate-root', 'engagement', 'domain-model'],
    evidence: promptEvidence('LTA-ARCH-003', 'Event-to-Engagement question'),
  },
  {
    libraryId: 'LTA-PROOF-004',
    originalPromptId: 'P-PROOF-004',
    title: 'Accepted is not paid',
    project: 'QuietPilot',
    timestamp: '2026-06-01T10:00:00.000Z',
    family: 'authority-and-proof',
    form: 'constraint',
    originalText: 'A proposal acceptance cannot be presented as payment settlement or readiness.',
    normalizedIntent: 'Keep commercial, provider, and operational proof domains separate.',
    hiddenProblem: 'Optimistic status labels collapse distinct business events into one misleading state.',
    principleIds: ['PRINCIPLE-EVIDENCE-BEFORE-CLAIMS', 'PRINCIPLE-ACCEPTED-TRUTH'],
    patternIds: ['PATTERN-PROOF-BOUNDARY'],
    lineageIds: ['LINEAGE-TRUTH-HIERARCHY'],
    impactScore: 97,
    reusabilityScore: 98,
    evidenceGrade: 'VERIFIED',
    tags: ['acceptance', 'payment', 'readiness'],
    evidence: promptEvidence('LTA-PROOF-004', 'Proof boundary constraint'),
  },
  {
    libraryId: 'LTA-BLAST-005',
    originalPromptId: 'P-BLAST-005',
    title: 'Map the commercial blast radius',
    project: 'QuotePilot',
    timestamp: '2026-08-09T10:00:00.000Z',
    family: 'blast-radius',
    form: 'probe',
    originalText: 'When one quote fact changes, what price, staff, inventory, rental, artifact, acceptance, and readiness dependencies become stale?',
    normalizedIntent: 'Simulate all downstream consequences before applying a commercial change.',
    hiddenProblem: 'A valid edit can silently invalidate previously trusted downstream records.',
    principleIds: ['PRINCIPLE-BLAST-RADIUS', 'PRINCIPLE-ACCEPTED-TRUTH'],
    patternIds: ['PATTERN-COMMERCIAL-CHANGE'],
    lineageIds: ['LINEAGE-COMMERCIAL-CHANGE'],
    impactScore: 100,
    reusabilityScore: 97,
    evidenceGrade: 'VERIFIED',
    tags: ['dependency-graph', 'change-authority', 'reconciliation'],
    evidence: promptEvidence('LTA-BLAST-005', 'Commercial blast-radius question'),
  },
  {
    libraryId: 'LTA-AI-006',
    originalPromptId: 'P-AI-006',
    title: 'AI recommends; authority decides',
    project: 'QuotePilot',
    timestamp: '2026-08-10T10:00:00.000Z',
    family: 'ai-governance',
    form: 'constraint',
    originalText: 'AI may parse and explain, but it may not silently price, save, accept, pay, book, or mark work ready.',
    normalizedIntent: 'Use models at advisory boundaries with explicit human confirmation.',
    hiddenProblem: 'Fluent model output can be mistaken for authoritative business state.',
    principleIds: ['PRINCIPLE-AI-ADVISORY'],
    patternIds: ['PATTERN-HUMAN-CONFIRMATION'],
    lineageIds: ['LINEAGE-TRUTH-HIERARCHY'],
    impactScore: 96,
    reusabilityScore: 100,
    evidenceGrade: 'VERIFIED',
    tags: ['ai', 'human-in-the-loop', 'authority'],
    evidence: promptEvidence('LTA-AI-006', 'AI authority boundary'),
  },
  {
    libraryId: 'LTA-UX-007',
    originalPromptId: 'P-UX-007',
    title: 'Expose one next safe decision',
    project: 'QuotePilot',
    timestamp: '2026-08-10T11:00:00.000Z',
    family: 'ux-and-experience',
    form: 'reframe',
    originalText: 'Do not make the operator manage every status. Interpret the evidence into one next best action with provenance.',
    normalizedIntent: 'Compress system complexity without hiding evidence boundaries.',
    hiddenProblem: 'Dense dashboards transfer cognition to the operator instead of resolving it.',
    principleIds: ['PRINCIPLE-EVIDENCE-BEFORE-CLAIMS'],
    patternIds: ['PATTERN-DECISION-GRAMMAR'],
    lineageIds: ['LINEAGE-COMMERCIAL-SPINE'],
    impactScore: 91,
    reusabilityScore: 96,
    evidenceGrade: 'SUPPORTED',
    tags: ['decision-cards', 'cognitive-load', 'provenance'],
    evidence: promptEvidence('LTA-UX-007', 'Decision grammar direction'),
  },
  {
    libraryId: 'LTA-RECOVERY-008',
    originalPromptId: 'P-RECOVERY-008',
    title: 'Recover the golden path',
    project: 'QuietPilot',
    timestamp: '2026-04-30T10:00:00.000Z',
    family: 'recovery',
    form: 'execution-contract',
    originalText: 'Keep, cut, and defer until one inquiry-to-readiness path is deterministic and supportable.',
    normalizedIntent: 'Reduce an overbuilt platform to one bounded commercial outcome.',
    hiddenProblem: 'Architectural breadth obscured the first usable product loop.',
    principleIds: ['PRINCIPLE-BOUNDED-SLICE'],
    patternIds: ['PATTERN-GOLDEN-PATH'],
    lineageIds: ['LINEAGE-COMMERCIAL-SPINE'],
    impactScore: 99,
    reusabilityScore: 97,
    evidenceGrade: 'VERIFIED',
    tags: ['scope-reduction', 'golden-path', 'recovery'],
    evidence: promptEvidence('LTA-RECOVERY-008', 'MVP recovery plan'),
  },
  {
    libraryId: 'LTA-VERIFY-009',
    originalPromptId: 'P-VERIFY-009',
    title: 'Prove what must never happen',
    project: 'QuietPilot',
    timestamp: '2026-06-07T10:00:00.000Z',
    family: 'verification',
    form: 'execution-contract',
    originalText: 'Add negative assertions: intake does not create a quote; sent is not accepted; browser return is not settlement; job creation is not readiness.',
    normalizedIntent: 'Verify forbidden inference as rigorously as desired behavior.',
    hiddenProblem: 'Positive tests can pass while the UI still implies unsupported business truth.',
    principleIds: ['PRINCIPLE-EVIDENCE-BEFORE-CLAIMS'],
    patternIds: ['PATTERN-PROOF-BOUNDARY'],
    lineageIds: ['LINEAGE-TRUTH-HIERARCHY'],
    impactScore: 97,
    reusabilityScore: 99,
    evidenceGrade: 'VERIFIED',
    tags: ['negative-tests', 'forbidden-inference', 'proof'],
    evidence: promptEvidence('LTA-VERIFY-009', 'Negative assertion harness'),
  },
  {
    libraryId: 'LTA-RELEASE-010',
    originalPromptId: 'P-RELEASE-010',
    title: 'Separate source from production truth',
    project: 'QuotePilot',
    timestamp: '2026-08-11T10:00:00.000Z',
    family: 'release-truth',
    form: 'constraint',
    originalText: 'Implemented, tested, deployed, enabled, provider-accepted, human-accepted, and commercially validated are separate states.',
    normalizedIntent: 'Prevent release language from overstating runtime or customer evidence.',
    hiddenProblem: 'Source presence and local tests were being read as production capability.',
    principleIds: ['PRINCIPLE-EVIDENCE-BEFORE-CLAIMS'],
    patternIds: ['PATTERN-TRUTH-TRIANGULATION'],
    lineageIds: ['LINEAGE-TRUTH-HIERARCHY'],
    impactScore: 95,
    reusabilityScore: 100,
    evidenceGrade: 'VERIFIED',
    tags: ['release', 'deployment', 'provider-proof'],
    evidence: promptEvidence('LTA-RELEASE-010', 'Release truth ladder'),
  },
  {
    libraryId: 'LTA-AGENT-011',
    originalPromptId: 'P-AGENT-011',
    title: 'One bounded discovery pass',
    project: 'Cross-project',
    timestamp: '2026-06-10T10:00:00.000Z',
    family: 'agent-orchestration',
    form: 'constraint',
    originalText: 'Inspect once, name exact files, patch or report blocked, validate narrowly, and stop when acceptance criteria are met.',
    normalizedIntent: 'Constrain agents to evidence-grounded, reviewable work.',
    hiddenProblem: 'Repeated rediscovery and speculative cleanup expanded scope and introduced collisions.',
    principleIds: ['PRINCIPLE-BOUNDED-SLICE'],
    patternIds: ['PATTERN-GOLDEN-PATH'],
    lineageIds: ['LINEAGE-TRUTH-HIERARCHY'],
    impactScore: 94,
    reusabilityScore: 100,
    evidenceGrade: 'VERIFIED',
    tags: ['agents', 'bounded-discovery', 'stop-condition'],
    evidence: promptEvidence('LTA-AGENT-011', 'Agent execution discipline'),
  },
  {
    libraryId: 'LTA-METHOD-012',
    originalPromptId: 'P-METHOD-012',
    title: 'Convert failures into repository rules',
    project: 'Cross-project',
    timestamp: '2026-07-01T10:00:00.000Z',
    family: 'methodology',
    form: 'reframe',
    originalText: 'What assumption failed, what control would prevent recurrence, and how should the repository remember it?',
    normalizedIntent: 'Transform defects and corrections into reusable institutional controls.',
    hiddenProblem: 'Without durable memory, agents repeat the same mistakes across sessions and projects.',
    principleIds: ['PRINCIPLE-BOUNDED-SLICE'],
    patternIds: ['PATTERN-FAILURE-TO-CONTROL'],
    lineageIds: ['LINEAGE-COMMERCIAL-CHANGE'],
    impactScore: 96,
    reusabilityScore: 100,
    evidenceGrade: 'SUPPORTED',
    tags: ['failure-memory', 'governance', 'learning-loop'],
    evidence: promptEvidence('LTA-METHOD-012', 'Failure memory rule'),
  },
  {
    libraryId: 'LTA-INQUISITOR-013',
    originalPromptId: 'P-AUDIT-013',
    title: 'Look to architecture, not documents',
    project: 'QuietPilot',
    timestamp: '2026-07-18T13:20:44.401Z',
    family: 'inquisitor',
    form: 'correction',
    originalText: 'LOOK TO THE ARCHITECTURE, NOT DOCUMENTS',
    normalizedIntent: 'Resolve conflicts using current imports, contracts, routes, tests, and runtime seams.',
    hiddenProblem: 'Stale narrative documents were masking implementation reality.',
    principleIds: ['PRINCIPLE-EVIDENCE-BEFORE-CLAIMS'],
    patternIds: ['PATTERN-TRUTH-TRIANGULATION'],
    lineageIds: ['LINEAGE-TRUTH-HIERARCHY'],
    impactScore: 92,
    reusabilityScore: 99,
    evidenceGrade: 'SUPPORTED',
    tags: ['correction', 'repository-reality', 'architecture'],
    evidence: promptEvidence('LTA-INQUISITOR-013', 'Architecture-first correction'),
  },
  {
    libraryId: 'LTA-AUTH-014',
    originalPromptId: 'P-AUTH-014',
    title: 'One authority per business truth',
    project: 'Cross-project',
    timestamp: '2026-08-05T10:00:00.000Z',
    family: 'authority-and-proof',
    form: 'constraint',
    originalText: 'Overlap in presentation is acceptable. Overlap in authority is not.',
    normalizedIntent: 'Assign one canonical owner to every consequential business fact.',
    hiddenProblem: 'QuotePilot and QuietPilot could independently mutate the same commercial or operational state.',
    principleIds: ['PRINCIPLE-ONE-AUTHORITY'],
    patternIds: ['PATTERN-COMMERCIAL-SPINE'],
    lineageIds: ['LINEAGE-COMMERCIAL-SPINE'],
    impactScore: 98,
    reusabilityScore: 100,
    evidenceGrade: 'SUPPORTED',
    tags: ['authority', 'product-boundary', 'handoff'],
    evidence: promptEvidence('LTA-AUTH-014', 'Cross-product authority rule'),
  },
  {
    libraryId: 'LTA-VERIFY-015',
    originalPromptId: 'P-VERIFY-015',
    title: 'Component correctness is not reachability',
    project: 'QuotePilot',
    timestamp: '2026-08-10T18:00:00.000Z',
    family: 'verification',
    form: 'correction',
    originalText: 'Trace the real route, auth, tenant, feature gate, application state, mounted component, action, and canonical write.',
    normalizedIntent: 'Verify the integrated user path rather than only isolated components.',
    hiddenProblem: 'A request panel passed unit tests but was dead in the actual application flow.',
    principleIds: ['PRINCIPLE-EVIDENCE-BEFORE-CLAIMS'],
    patternIds: ['PATTERN-REAL-FLOW'],
    lineageIds: ['LINEAGE-COMMERCIAL-CHANGE'],
    impactScore: 91,
    reusabilityScore: 98,
    evidenceGrade: 'VERIFIED',
    tags: ['integration', 'route', 'browser-verification'],
    evidence: promptEvidence('LTA-VERIFY-015', 'Real-flow reachability lesson'),
  },
  {
    libraryId: 'LTA-AI-016',
    originalPromptId: 'P-AI-016',
    title: 'Deterministic floor beneath model assistance',
    project: 'QuotePilot',
    timestamp: '2026-08-11T10:00:00.000Z',
    family: 'ai-governance',
    form: 'constraint',
    originalText: 'Keep a deterministic availability floor; model suggestions degrade honestly and require confirmation.',
    normalizedIntent: 'Avoid making core workflow availability depend on model success.',
    hiddenProblem: 'Provider failure or malformed output could block ordinary intake.',
    principleIds: ['PRINCIPLE-AI-ADVISORY'],
    patternIds: ['PATTERN-HUMAN-CONFIRMATION'],
    lineageIds: ['LINEAGE-TRUTH-HIERARCHY'],
    impactScore: 90,
    reusabilityScore: 97,
    evidenceGrade: 'VERIFIED',
    tags: ['deterministic-fallback', 'provider-failure', 'ai'],
    evidence: promptEvidence('LTA-AI-016', 'Deterministic AI fallback'),
  },
  {
    libraryId: 'LTA-UX-017',
    originalPromptId: 'P-UX-017',
    title: 'Living Event as the visible operating object',
    project: 'QuietPilot',
    timestamp: '2026-08-12T02:34:25.000Z',
    family: 'ux-and-experience',
    form: 'reframe',
    originalText: 'Show one event becoming real as evidence arrives and consequences propagate.',
    normalizedIntent: 'Translate proof-governed architecture into an understandable visual narrative.',
    hiddenProblem: 'A conventional dashboard failed to communicate the causal power of the system.',
    principleIds: ['PRINCIPLE-BLAST-RADIUS'],
    patternIds: ['PATTERN-DECISION-GRAMMAR'],
    lineageIds: ['LINEAGE-COMMERCIAL-SPINE'],
    impactScore: 88,
    reusabilityScore: 82,
    evidenceGrade: 'VERIFIED',
    tags: ['living-event', 'visual-story', 'readiness'],
    evidence: promptEvidence('LTA-UX-017', 'Living Event experience'),
  },
  {
    libraryId: 'LTA-ARCH-018',
    originalPromptId: 'P-ARCH-018',
    title: 'Integrations carry immutable facts, not shared tables',
    project: 'Cross-project',
    timestamp: '2026-08-05T12:00:00.000Z',
    family: 'architecture',
    form: 'constraint',
    originalText: 'QuotePilot publishes an immutable accepted snapshot; QuietPilot consumes it idempotently and preserves provenance.',
    normalizedIntent: 'Create a contract boundary between commercial and operational products.',
    hiddenProblem: 'Shared persistence would create conflicting ownership and fragile coupling.',
    principleIds: ['PRINCIPLE-ONE-AUTHORITY', 'PRINCIPLE-ACCEPTED-TRUTH'],
    patternIds: ['PATTERN-COMMERCIAL-SPINE'],
    lineageIds: ['LINEAGE-COMMERCIAL-SPINE'],
    impactScore: 95,
    reusabilityScore: 94,
    evidenceGrade: 'SUPPORTED',
    tags: ['integration-contract', 'snapshot', 'idempotency'],
    evidence: promptEvidence('LTA-ARCH-018', 'Immutable handoff contract'),
  },
  {
    libraryId: 'LTA-RECOVERY-019',
    originalPromptId: 'P-RECOVERY-019',
    title: 'Make the smallest safe patch',
    project: 'Cross-project',
    timestamp: '2026-06-15T10:00:00.000Z',
    family: 'recovery',
    form: 'constraint',
    originalText: 'Do not redesign, invent routes, or fix unrelated work. Change only the proven insertion point.',
    normalizedIntent: 'Retire one evidenced defect without widening the blast radius.',
    hiddenProblem: 'Broad repair prompts triggered unrelated refactors and made verification less attributable.',
    principleIds: ['PRINCIPLE-BOUNDED-SLICE'],
    patternIds: ['PATTERN-GOLDEN-PATH'],
    lineageIds: ['LINEAGE-TRUTH-HIERARCHY'],
    impactScore: 92,
    reusabilityScore: 100,
    evidenceGrade: 'VERIFIED',
    tags: ['smallest-safe-patch', 'scope', 'rollback'],
    evidence: promptEvidence('LTA-RECOVERY-019', 'Smallest safe patch rule'),
  },
  {
    libraryId: 'LTA-METHOD-020',
    originalPromptId: 'P-METHOD-020',
    title: 'Build a reusable architecting constitution',
    project: 'Limitless Architecting OS',
    timestamp: '2026-08-15T12:00:00.000Z',
    family: 'methodology',
    form: 'execution-contract',
    originalText: 'Turn the prompts, failures, controls, and lineages into a system that makes the next project smarter.',
    normalizedIntent: 'Convert development history into compounding architectural intelligence.',
    hiddenProblem: 'Important reasoning was trapped in conversations and had to be rediscovered.',
    principleIds: ['PRINCIPLE-EVIDENCE-BEFORE-CLAIMS', 'PRINCIPLE-BOUNDED-SLICE'],
    patternIds: ['PATTERN-FAILURE-TO-CONTROL'],
    lineageIds: ['LINEAGE-TRUTH-HIERARCHY'],
    impactScore: 100,
    reusabilityScore: 100,
    evidenceGrade: 'SUPPORTED',
    tags: ['knowledge-system', 'prompt-compiler', 'creator-profile'],
    evidence: promptEvidence('LTA-METHOD-020', 'Limitless Architecting OS thesis'),
  },
];

export const principles: KnowledgeEntity[] = [
  {
    id: 'PRINCIPLE-EVIDENCE-BEFORE-CLAIMS',
    kind: 'principle',
    title: 'Evidence before claims',
    statement: 'The system may state only what current authoritative evidence supports.',
    description: 'Implementation, deployment, provider acceptance, human acceptance, and business outcome remain separate proof domains.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-INQUISITOR-002', 'LTA-PROOF-004', 'LTA-VERIFY-009', 'LTA-RELEASE-010'],
    projectIds: ['QuietPilot', 'QuotePilot'],
    tags: ['proof', 'truth', 'claims'],
  },
  {
    id: 'PRINCIPLE-ONE-AUTHORITY',
    kind: 'principle',
    title: 'One canonical authority per business truth',
    statement: 'Many surfaces may present a fact, but only one bounded context may own its mutation.',
    description: 'The rule prevents product overlap, conflicting state, and provider-driven corruption of source truth.',
    evidenceGrade: 'SUPPORTED',
    status: 'active',
    promptIds: ['LTA-AUTH-014', 'LTA-ARCH-018', 'LTA-ARCH-003'],
    projectIds: ['QuietPilot', 'QuotePilot'],
    tags: ['authority', 'bounded-context'],
  },
  {
    id: 'PRINCIPLE-ACCEPTED-TRUTH',
    kind: 'principle',
    title: 'Accepted commercial truth is immutable',
    statement: 'A changed commitment creates a new version; it never rewrites what the customer accepted.',
    description: 'Jobs and operational obligations derive from an explicit accepted commercial snapshot.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-PROOF-004', 'LTA-BLAST-005', 'LTA-ARCH-018'],
    projectIds: ['QuietPilot', 'QuotePilot'],
    tags: ['versions', 'acceptance', 'snapshot'],
  },
  {
    id: 'PRINCIPLE-AI-ADVISORY',
    kind: 'principle',
    title: 'Advisory intelligence cannot establish authority',
    statement: 'Models may parse, suggest, compare, and explain; canonical services and accountable humans decide.',
    description: 'Every AI result is untrusted candidate material until validated and explicitly promoted.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-AI-006', 'LTA-AI-016'],
    projectIds: ['QuietPilot', 'QuotePilot', 'Limitless Architecting OS'],
    tags: ['ai', 'human-review', 'candidate'],
  },
  {
    id: 'PRINCIPLE-BLAST-RADIUS',
    kind: 'principle',
    title: 'Every consequential change has a blast radius',
    statement: 'Before mutation, identify every dependent decision, projection, artifact, and obligation that may become stale.',
    description: 'Change safety requires simulation, authorization, named invalidation, and exact reconciliation.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-BLAST-005', 'LTA-UX-017'],
    projectIds: ['QuietPilot', 'QuotePilot'],
    tags: ['dependency', 'change', 'reconciliation'],
  },
  {
    id: 'PRINCIPLE-BOUNDED-SLICE',
    kind: 'principle',
    title: 'Prefer the smallest complete, attributable slice',
    statement: 'Inspect once, change only evidenced insertion points, validate, report, and stop.',
    description: 'Scope discipline preserves attribution, rollback, reviewability, and agent collision safety.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-RECOVERY-008', 'LTA-AGENT-011', 'LTA-RECOVERY-019'],
    projectIds: ['QuietPilot', 'QuotePilot'],
    tags: ['scope', 'delivery', 'verification'],
  },
];

export const patterns: KnowledgeEntity[] = [
  {
    id: 'PATTERN-COMMERCIAL-SPINE',
    kind: 'pattern',
    title: 'Commercial-to-operational spine',
    statement: 'Carry one attributable commitment from inquiry through delivery without collapsing domain authorities.',
    description: 'A lifecycle pattern for service commerce and clean cross-product handoff.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-VISION-001', 'LTA-AUTH-014', 'LTA-ARCH-018'],
    projectIds: ['QuietPilot', 'QuotePilot'],
    tags: ['commercial-spine', 'handoff'],
  },
  {
    id: 'PATTERN-TRUTH-TRIANGULATION',
    kind: 'pattern',
    title: 'Intent, enforcement, runtime triangulation',
    statement: 'Compare the product claim with code guarantees and observed runtime evidence.',
    description: 'A forensic audit pattern for detecting decorative architecture and unsupported claims.',
    evidenceGrade: 'SUPPORTED',
    status: 'active',
    promptIds: ['LTA-INQUISITOR-002', 'LTA-INQUISITOR-013', 'LTA-RELEASE-010'],
    projectIds: ['QuietPilot', 'QuotePilot'],
    tags: ['audit', 'runtime', 'truth'],
  },
  {
    id: 'PATTERN-COMMERCIAL-CHANGE',
    kind: 'pattern',
    title: 'Dependency-aware commercial change',
    statement: 'Simulate, authorize, apply atomically, invalidate named dependencies, and reconcile exact evidence.',
    description: 'A receipt-driven protocol for preserving trusted downstream artifacts after consequential edits.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-BLAST-005'],
    projectIds: ['QuotePilot'],
    tags: ['change-authority', 'receipts', 'idempotency'],
  },
  {
    id: 'PATTERN-PROOF-BOUNDARY',
    kind: 'pattern',
    title: 'Proof-boundary interface contract',
    statement: 'For every product claim, declare required evidence, allowed wording, forbidden wording, and verification.',
    description: 'Makes epistemic correctness part of UX and test architecture.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-PROOF-004', 'LTA-VERIFY-009'],
    projectIds: ['QuietPilot', 'QuotePilot'],
    tags: ['copy', 'tests', 'evidence'],
  },
  {
    id: 'PATTERN-REAL-FLOW',
    kind: 'pattern',
    title: 'Real-flow reachability verification',
    statement: 'Verify the complete route-to-authority-to-component-to-write chain, not only isolated units.',
    description: 'Prevents component-correct but product-dead capabilities.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-VERIFY-015'],
    projectIds: ['QuotePilot'],
    tags: ['integration', 'browser', 'reachability'],
  },
  {
    id: 'PATTERN-GOLDEN-PATH',
    kind: 'pattern',
    title: 'Golden-path constrainment',
    statement: 'Reduce competing routes until one canonical mutation path proves the primary customer outcome.',
    description: 'A recovery pattern for overbuilt repositories and ambiguous service ownership.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-RECOVERY-008', 'LTA-AGENT-011', 'LTA-RECOVERY-019'],
    projectIds: ['QuietPilot'],
    tags: ['recovery', 'scope', 'canonical-path'],
  },
  {
    id: 'PATTERN-HUMAN-CONFIRMATION',
    kind: 'pattern',
    title: 'Model suggestion with deterministic floor',
    statement: 'Keep the core workflow available without AI and require confirmation before model output touches a draft.',
    description: 'A safe AI integration pattern for consequential business workflows.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-AI-006', 'LTA-AI-016'],
    projectIds: ['QuotePilot', 'Limitless Architecting OS'],
    tags: ['ai', 'fallback', 'confirmation'],
  },
  {
    id: 'PATTERN-FAILURE-TO-CONTROL',
    kind: 'pattern',
    title: 'Failure-to-control promotion',
    statement: 'Convert verified failure into root cause, prevention rule, test, and reusable execution module.',
    description: 'Compounds engineering learning across agent sessions and products.',
    evidenceGrade: 'SUPPORTED',
    status: 'active',
    promptIds: ['LTA-METHOD-012', 'LTA-METHOD-020'],
    projectIds: ['QuietPilot', 'QuotePilot', 'Limitless Architecting OS'],
    tags: ['learning', 'failure-memory', 'governance'],
  },
  {
    id: 'PATTERN-DECISION-GRAMMAR',
    kind: 'pattern',
    title: 'Claim → basis → impact → action',
    statement: 'Present one interpreted claim, its evidence basis, consequence, provenance, and safe actions.',
    description: 'A cognitive-compression pattern for complex operational systems.',
    evidenceGrade: 'SUPPORTED',
    status: 'active',
    promptIds: ['LTA-UX-007', 'LTA-UX-017'],
    projectIds: ['QuietPilot', 'QuotePilot'],
    tags: ['ux', 'decision', 'provenance'],
  },
  {
    id: 'PATTERN-ROOT-OBJECT-CUTOVER',
    kind: 'pattern',
    title: 'Coordinated root-object cutover',
    statement: 'Rename the authority root across schema, contracts, routes, jobs, audit, cache, and UI as one governed migration.',
    description: 'Avoids transitional aliases becoming permanent competing identities.',
    evidenceGrade: 'VERIFIED',
    status: 'active',
    promptIds: ['LTA-ARCH-003'],
    projectIds: ['QuietPilot'],
    tags: ['migration', 'aggregate-root', 'coordination'],
  },
];

export const failures: FailureRecord[] = [
  {
    failureId: 'FAIL-001',
    title: 'Component correct, feature unreachable',
    observedIn: 'QuotePilot client change-request panel',
    trigger: 'Isolated component tests passed while the production edit flow never mounted the panel.',
    rootCause: 'The route-to-application-state wiring omitted the exact portal decision context.',
    correction: 'Carry the canonical presentation context through the real edit entry point.',
    control: 'Require route, auth, tenant, feature gate, state, mount, interaction, and canonical write verification.',
    generalizedRule: 'Component correctness does not establish feature reachability.',
    evidenceGrade: 'VERIFIED',
    relatedPromptIds: ['LTA-VERIFY-015'],
  },
  {
    failureId: 'FAIL-002',
    title: 'Documentation outran repository reality',
    observedIn: 'QuietPilot architecture and status descriptions',
    trigger: 'Narrative documents described target or stale state as though it were current implementation.',
    rootCause: 'Documentation was treated as primary evidence instead of being reconciled against code and commits.',
    correction: 'Trace current schemas, imports, services, routes, tests, and history before making claims.',
    control: 'Apply the intent/enforcement/runtime truth hierarchy and record conflicts explicitly.',
    generalizedRule: 'Documentation can direct work; it cannot prove runtime truth.',
    evidenceGrade: 'SUPPORTED',
    relatedPromptIds: ['LTA-INQUISITOR-002', 'LTA-INQUISITOR-013'],
  },
  {
    failureId: 'FAIL-003',
    title: 'Architecture breadth obscured the paid path',
    observedIn: 'Early QuietPilot platform evolution',
    trigger: 'Many modules existed while the end-to-end customer outcome remained difficult to demonstrate.',
    rootCause: 'Feature and platform breadth were allowed to outrun one canonical commercial workflow.',
    correction: 'Keep, cut, and defer around the inquiry-to-readiness golden path.',
    control: 'Require every implementation slice to name its customer outcome, authoritative transition, proof, and rollback.',
    generalizedRule: 'Architecture is not progress unless it advances a verifiable customer outcome.',
    evidenceGrade: 'SUPPORTED',
    relatedPromptIds: ['LTA-RECOVERY-008', 'LTA-AGENT-011'],
  },
];

export const lineages: ArchitectingLineage[] = [
  {
    lineageId: 'LINEAGE-COMMERCIAL-SPINE',
    title: 'From quoting tool to proof-governed operating system',
    summary: 'A category reframe became one commercial spine, bounded authorities, and an immutable handoff between products.',
    project: 'QuietPilot + QuotePilot',
    steps: [
      { id: 'spine-prompt', type: 'prompt', title: 'Reject the inherited category', detail: 'What gets sold must determine delivery.', evidenceGrade: 'VERIFIED' },
      { id: 'spine-contradiction', type: 'contradiction', title: 'Sales and operations lose continuity', detail: 'Disconnected tools cannot prove that execution matches the accepted offer.', evidenceGrade: 'SUPPORTED' },
      { id: 'spine-principle', type: 'principle', title: 'One authority per truth', detail: 'Commercial and operational contexts retain separate ownership.', evidenceGrade: 'SUPPORTED' },
      { id: 'spine-decision', type: 'decision', title: 'Immutable accepted snapshot handoff', detail: 'QuotePilot creates; QuietPilot consumes and preserves provenance.', evidenceGrade: 'SUPPORTED' },
      { id: 'spine-proof', type: 'proof', title: 'Job binds to accepted source', detail: 'Workspace, engagement, quote, version, proposal, and snapshot identities must agree.', evidenceGrade: 'VERIFIED' },
    ],
    edges: [
      { from: 'spine-prompt', to: 'spine-contradiction', label: 'exposed' },
      { from: 'spine-contradiction', to: 'spine-principle', label: 'produced' },
      { from: 'spine-principle', to: 'spine-decision', label: 'governed' },
      { from: 'spine-decision', to: 'spine-proof', label: 'enforced by' },
    ],
  },
  {
    lineageId: 'LINEAGE-COMMERCIAL-CHANGE',
    title: 'Commercial blast radius to change authority',
    summary: 'A guest-count question became a deterministic dependency graph and receipt-driven change protocol.',
    project: 'QuotePilot',
    steps: [
      { id: 'change-prompt', type: 'prompt', title: 'What does this change touch?', detail: 'Map price, margin, staffing, inventory, artifacts, acceptance, and readiness.', evidenceGrade: 'VERIFIED' },
      { id: 'change-contradiction', type: 'contradiction', title: 'Valid edit, stale dependents', detail: 'A quote can be valid while downstream artifacts become wrong.', evidenceGrade: 'VERIFIED' },
      { id: 'change-principle', type: 'principle', title: 'Every change has a blast radius', detail: 'Consequences must be identified before mutation.', evidenceGrade: 'VERIFIED' },
      { id: 'change-decision', type: 'decision', title: 'Simulate → authorize → apply → invalidate → reconcile', detail: 'Use exact identities and immutable receipts.', evidenceGrade: 'VERIFIED' },
      { id: 'change-failure', type: 'failure', title: 'Correct component was unreachable', detail: 'Integrated wiring did not carry the required state.', evidenceGrade: 'VERIFIED' },
      { id: 'change-control', type: 'control', title: 'Real-flow reachability', detail: 'Verify the complete route-to-write chain.', evidenceGrade: 'VERIFIED' },
    ],
    edges: [
      { from: 'change-prompt', to: 'change-contradiction', label: 'revealed' },
      { from: 'change-contradiction', to: 'change-principle', label: 'formed' },
      { from: 'change-principle', to: 'change-decision', label: 'became' },
      { from: 'change-decision', to: 'change-failure', label: 'implementation exposed' },
      { from: 'change-failure', to: 'change-control', label: 'created' },
    ],
  },
  {
    lineageId: 'LINEAGE-TRUTH-HIERARCHY',
    title: 'From confident claims to evidence grades',
    summary: 'Repeated overclaiming risks became a shared truth hierarchy, negative assertions, and candidate review workflow.',
    project: 'Cross-project',
    steps: [
      { id: 'truth-prompt', type: 'prompt', title: 'Is the system lying?', detail: 'Compare intent, enforcement, and runtime.', evidenceGrade: 'VERIFIED' },
      { id: 'truth-principle', type: 'principle', title: 'Evidence before claims', detail: 'Every assertion needs an attributable proof boundary.', evidenceGrade: 'VERIFIED' },
      { id: 'truth-decision', type: 'decision', title: 'Separate authority layers', detail: 'Historical evidence, canonical knowledge, AI candidates, and projections never collapse.', evidenceGrade: 'SUPPORTED' },
      { id: 'truth-implementation', type: 'implementation', title: 'Proof registry and review center', detail: 'Allowed claims, forbidden inferences, evidence grades, and human promotion.', evidenceGrade: 'SUPPORTED' },
      { id: 'truth-proof', type: 'proof', title: 'Negative assertions', detail: 'Tests prove both required behavior and forbidden inference.', evidenceGrade: 'VERIFIED' },
    ],
    edges: [
      { from: 'truth-prompt', to: 'truth-principle', label: 'generated' },
      { from: 'truth-principle', to: 'truth-decision', label: 'governed' },
      { from: 'truth-decision', to: 'truth-implementation', label: 'implemented as' },
      { from: 'truth-implementation', to: 'truth-proof', label: 'verified by' },
    ],
  },
];

export const profileClaims: ProfileClaim[] = [
  {
    claimId: 'PROFILE-001',
    claim: 'Operates primarily as a product systems architect rather than a feature-by-feature developer.',
    category: 'identity',
    evidenceGrade: 'SUPPORTED',
    confidence: 0.92,
    evidence: promptEvidence('PROFILE-001', 'Cross-project category and authority prompts'),
    alternativeExplanation: 'Some system-level behavior may be a response to repeated agent failures rather than an original preference.',
  },
  {
    claimId: 'PROFILE-002',
    claim: 'Uses adversarial questions to expose contradictions between product claims, code enforcement, and runtime evidence.',
    category: 'reasoning',
    evidenceGrade: 'VERIFIED',
    confidence: 0.98,
    evidence: promptEvidence('PROFILE-002', 'Intent/enforcement/runtime audit prompts'),
    alternativeExplanation: 'The style may partly reflect high sensitivity to unreliable agent reports.',
  },
  {
    claimId: 'PROFILE-003',
    claim: 'Naturally models second-order consequences and dependency blast radius.',
    category: 'strength',
    evidenceGrade: 'VERIFIED',
    confidence: 0.96,
    evidence: promptEvidence('PROFILE-003', 'Commercial blast-radius lineage'),
    alternativeExplanation: 'The pattern is strongest in commercial workflow projects and may not generalize equally to every domain.',
  },
  {
    claimId: 'PROFILE-004',
    claim: 'Alternates between very short steering probes and long constitutional execution contracts.',
    category: 'prompting',
    evidenceGrade: 'SUPPORTED',
    confidence: 0.94,
    evidence: promptEvidence('PROFILE-004', 'Prompt corpus form analysis'),
    alternativeExplanation: 'Some short prompts depend on context from prior agent turns and may be less reusable than they appear.',
  },
  {
    claimId: 'PROFILE-005',
    claim: 'Directs agents to convert verified failures into tests, repository rules, and reusable execution constraints.',
    category: 'collaboration',
    evidenceGrade: 'SUPPORTED',
    confidence: 0.91,
    evidence: promptEvidence('PROFILE-005', 'Failure-memory and reachability controls'),
    alternativeExplanation: 'Not every documented control has yet been proven across multiple independent projects.',
  },
  {
    claimId: 'PROFILE-006',
    claim: 'Risks allowing architectural sophistication to outrun customer validation and onboarding simplicity.',
    category: 'risk',
    evidenceGrade: 'INFERRED',
    confidence: 0.83,
    evidence: promptEvidence('PROFILE-006', 'Golden-path recovery evidence'),
    alternativeExplanation: 'Early platform breadth may have been intentional research investment rather than uncontrolled expansion.',
  },
];

export const compilerModules: CompilerModule[] = [
  {
    moduleId: 'MODULE-REPOSITORY-REALITY',
    title: 'Repository Reality First',
    category: 'discovery',
    purpose: 'Prevent architecture from being based on stale documentation or assumed files.',
    contract: ['Inspect current code, tests, routes, schemas, and history before prescribing.', 'List exact evidence inspected.', 'Record documentation conflicts.'],
    conflictsWith: [],
    sourcePrincipleIds: ['PRINCIPLE-EVIDENCE-BEFORE-CLAIMS'],
    evidenceGrade: 'VERIFIED',
  },
  {
    moduleId: 'MODULE-BOUNDED-DISCOVERY',
    title: 'Bounded Discovery',
    category: 'execution',
    purpose: 'Keep investigation attributable and stop repeated repository wandering.',
    contract: ['Perform one bounded discovery pass.', 'Patch when the insertion point is proven; otherwise report blocked.', 'Do not repeat broad discovery loops.'],
    conflictsWith: [],
    sourcePrincipleIds: ['PRINCIPLE-BOUNDED-SLICE'],
    evidenceGrade: 'VERIFIED',
  },
  {
    moduleId: 'MODULE-CANONICAL-AUTHORITY',
    title: 'Canonical Authority',
    category: 'architecture',
    purpose: 'Assign one owner to every consequential business truth.',
    contract: ['Name the authoritative record and service.', 'Separate read projections from mutation authority.', 'Reject client or provider inference as source authority.'],
    conflictsWith: [],
    sourcePrincipleIds: ['PRINCIPLE-ONE-AUTHORITY'],
    evidenceGrade: 'SUPPORTED',
  },
  {
    moduleId: 'MODULE-PROOF-BOUNDARY',
    title: 'Proof Boundary',
    category: 'verification',
    purpose: 'Constrain product claims to attributable evidence.',
    contract: ['Name required evidence for every claim.', 'Define allowed and forbidden wording.', 'Add negative assertions for unsupported inferences.'],
    conflictsWith: [],
    sourcePrincipleIds: ['PRINCIPLE-EVIDENCE-BEFORE-CLAIMS'],
    evidenceGrade: 'VERIFIED',
  },
  {
    moduleId: 'MODULE-BLAST-RADIUS',
    title: 'Change Blast Radius',
    category: 'architecture',
    purpose: 'Identify downstream consequences before mutation.',
    contract: ['Enumerate affected facts, decisions, projections, and artifacts.', 'Classify review versus stale dependencies.', 'Define invalidation and reconciliation evidence.'],
    conflictsWith: [],
    sourcePrincipleIds: ['PRINCIPLE-BLAST-RADIUS'],
    evidenceGrade: 'VERIFIED',
  },
  {
    moduleId: 'MODULE-AI-ADVISORY',
    title: 'AI Advisory Boundary',
    category: 'ai-governance',
    purpose: 'Use model intelligence without granting it business authority.',
    contract: ['Treat model output as untrusted candidate material.', 'Require schema validation and explicit human promotion.', 'Keep a deterministic fallback where the workflow is critical.'],
    conflictsWith: [],
    sourcePrincipleIds: ['PRINCIPLE-AI-ADVISORY'],
    evidenceGrade: 'VERIFIED',
  },
  {
    moduleId: 'MODULE-REAL-FLOW',
    title: 'Real-Flow Reachability',
    category: 'verification',
    purpose: 'Prove that integrated users can reach and complete the capability.',
    contract: ['Trace route, auth, tenant, gate, data, state, mount, interaction, and write.', 'Retain isolated tests but do not treat them as integrated proof.', 'Capture browser evidence for material UX paths.'],
    conflictsWith: [],
    sourcePrincipleIds: ['PRINCIPLE-EVIDENCE-BEFORE-CLAIMS'],
    evidenceGrade: 'VERIFIED',
  },
  {
    moduleId: 'MODULE-ROLLBACK-STOP',
    title: 'Rollback and Stop Condition',
    category: 'delivery',
    purpose: 'Make the change reversible and prevent post-acceptance scope drift.',
    contract: ['Name the rollback boundary.', 'Stop when observable acceptance criteria pass.', 'Do not perform unrelated cleanup or speculative refactoring.'],
    conflictsWith: [],
    sourcePrincipleIds: ['PRINCIPLE-BOUNDED-SLICE'],
    evidenceGrade: 'VERIFIED',
  },
];

export const projects = [
  { id: 'QuietPilot', name: 'QuietPilot', role: 'Operational execution and verified readiness', status: 'active' },
  { id: 'QuotePilot', name: 'QuotePilot', role: 'Commercial decision and accepted truth', status: 'active' },
  { id: 'Limitless Architecting OS', name: 'Limitless Architecting OS', role: 'Architecting intelligence and prompt compiler', status: 'walking-skeleton' },
] as const;

export const fixtureSummary = {
  prompts: promptRecords.length,
  principles: principles.length,
  patterns: patterns.length,
  failures: failures.length,
  lineages: lineages.length,
  profileClaims: profileClaims.length,
  compilerModules: compilerModules.length,
};
